---
- name: Instalar Apache2
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes

- name: Crear directorio para la página web personalizada
  ansible.builtin.file:
    path: /var/www/html/innova_intranet
    state: directory
    mode: '0755'

- name: Renderizar y copiar index.html personalizado
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/innova_intranet/index.html
    mode: '0644'
  notify: Reiniciar Apache2

- name: Configurar Virtual Host de Apache para InnovaSys
  ansible.builtin.copy:
    content: |
      <VirtualHost *:80>
          DocumentRoot /var/www/html/innova_intranet
          <Directory /var/www/html/innova_intranet>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>
    dest: /etc/apache2/sites-available/innovasys.conf
    mode: '0644'
  notify: Reiniciar Apache2

- name: Deshabilitar sitio por defecto de Apache
  ansible.builtin.command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: Reiniciar Apache2

- name: Habilitar sitio InnovaSys
  ansible.builtin.command: a2ensite innovasys.conf
  args:
    creates: /etc/apache2/sites-enabled/innovasys.conf
  notify: Reiniciar Apache2

- name: Asegurar que Apache2 esté iniciado y habilitado en el arranque
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
